#
# Bluetooth settings
#
# Max available profile +1 (+1 is for peripheral)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

#
# Battery reporting
#
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORTING_FETCH_MODE_STATE_OF_CHARGE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y

#
# Idle/Deep Sleep
#
CONFIG_ZMK_SLEEP=y
# 30s (Not so important actually..)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# 30min: Longer period is suggested for better usability
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

#
# LED https://github.com/cormoran/zmk-driver-animation
#
CONFIG_LED_STRIP=y
CONFIG_ZMK_ANIMATION=y
CONFIG_SPI=y
CONFIG_ZMK_DRIVER_EXT_POWER_TRANSIENT=y

#
# Default layer module https://github.com/cormoran/zmk-feature-default-layer
#
CONFIG_ZMK_DEFAULT_LAYER=y
CONFIG_ZMK_DEFAULT_LAYER_MIN_INDEX=0
CONFIG_ZMK_DEFAULT_LAYER_MAX_INDEX=4

# --------------------------------------------------------
#
#
# Settings only available in cormoran's ZMK fork
#
#
# --------------------------------------------------------

# Enable half-duplex UART mode provided
CONFIG_ZMK_SPLIT_WIRED_UART_MODE_INTERRUPT=y
# Enable split relay to unlock interacting with peripheral
CONFIG_ZMK_SPLIT_RELAY_EVENT=y

# For zephyr4.1 CONSOLE is enabled by default but not required
CONFIG_CONSOLE=n

#
# ZMK modules ready for custom RPC protocol
#

# https://github.com/cormoran/zmk-module-runtime-input-processor
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y
# https://github.com/cormoran/zmk-module-ble-management
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
# https://github.com/cormoran/zmk-module-settings-rpc
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y
# https://github.com/cormoran/zmk-feature-input-stream
CONFIG_ZMK_INPUT_STREAM_FEATURE=y
CONFIG_ZMK_INPUT_STREAM_FEATURE_STUDIO_RPC=y
# https://github.com/cormoran/zmk-feature-module-physical-layout
CONFIG_ZMK_PHYSICAL_LAYOUTS_FEATURE=y
CONFIG_ZMK_PHYSICAL_LAYOUTS_FEATURE_STUDIO_RPC=y
# https://github.com/cormoran/zmk-feature-custom-settings
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_SPLIT_RPC_RELAY=y
CONFIG_ZMK_CUSTOM_SETTINGS_STUDIO_RPC=y
# https://github.com/cormoran/zmk-feature-runtime-combo
CONFIG_ZMK_RUNTIME_COMBO=y
CONFIG_ZMK_RUNTIME_COMBO_STUDIO_RPC=y
# https://github.com/cormoran/zmk-feature-runtime-macro
CONFIG_ZMK_RUNTIME_MACRO=y
CONFIG_ZMK_RUNTIME_MACRO_STUDIO_RPC=y
CONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y
# https://github.com/cormoran/zmk-module-battery-history
# TODO: Re-enable after resolving slow save issue
# CONFIG_ZMK_BATTERY_HISTORY=y
# CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=y

#
# Adjustment for Custom RPC Protocol & Split Relay support
#

# Shorten time until persisting setting to prevent data loss after edit setting.
# WARNING: The downside is that it may cause more frequent writes to flash which may reduce flash lifespan.
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
# Increase stack size to prevent stack overflow for split relay feature
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=768
# Increase stack size for low priority thread to prevent stack overflow when encoding large notification body for custom rpc.
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=2048
# Increase RPC buffers for zmk-feature-custom-settings and runtime macro payloads.
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=192
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=256
CONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=192
